Repository mishael-o/Dapper.SimpleSqlBuilder, pull requests merged in 2023-12, with the labels that each got.

#66 Typo in the README.md code example
  README.md
Labels: documentation

#67 Upgraded NuGet packages version. Bumped `Dapper` to version `2.1.24`
  src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
  src/Builder/Directory.Build.props
  src/Builder/SimpleSqlBuilder.DependencyInjection/SimpleSqlBuilder.DependencyInjection.csproj
  src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
  src/Builder/SimpleSqlBuilder/Core/SqlFormatter.cs
  src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
  src/Tests/Directory.Build.props
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
  src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests.csproj
Labels: enhancement

#68 .NET 8 support added to the library
  .github/workflows/ci-cd.yml
  README.md
  src/Benchmark/SimpleSqlBuilder.BenchMark/README.md
  src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
  src/Builder/SimpleSqlBuilder.DependencyInjection/GlobalSuppressions.cs
  src/Builder/SimpleSqlBuilder.DependencyInjection/SimpleSqlBuilder.DependencyInjection.csproj
  src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
  src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/Common/ProductGenerator.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/GlobalSuppressions.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlFluentTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTestsFixture.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlFluentTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTestsFixture.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlFluentTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTestsFixture.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
  src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests.csproj
  src/Tests/UnitTests/SimpleSqlBuilder.UnitTestHelpers/SimpleSqlBuilder.UnitTestHelpers.csproj
  src/Tests/UnitTests/SimpleSqlBuilder.UnitTestHelpers/XUnit/PriorityOrderer.cs
  src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/SimpleSqlBuilder.UnitTests.csproj
  src/version.json
Labels: feature

#69 Minor release 3.5
  .github/workflows/ci-cd.yml
  README.md
  src/Benchmark/SimpleSqlBuilder.BenchMark/README.md
  src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
  src/Builder/Directory.Build.props
  src/Builder/SimpleSqlBuilder.DependencyInjection/GlobalSuppressions.cs
  src/Builder/SimpleSqlBuilder.DependencyInjection/SimpleSqlBuilder.DependencyInjection.csproj
  src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
  src/Builder/SimpleSqlBuilder/Core/SqlFormatter.cs
  src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
  src/Tests/Directory.Build.props
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/Common/ProductGenerator.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/GlobalSuppressions.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlFluentTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTestsFixture.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlFluentTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTestsFixture.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlFluentTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTests.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTestsFixture.cs
  src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
  src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests.csproj
  src/Tests/UnitTests/SimpleSqlBuilder.UnitTestHelpers/SimpleSqlBuilder.UnitTestHelpers.csproj
  src/Tests/UnitTests/SimpleSqlBuilder.UnitTestHelpers/XUnit/PriorityOrderer.cs
  src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/SimpleSqlBuilder.UnitTests.csproj
  src/version.json
Labels: ignore-for-release
